version: '3.7'

services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT:-80}
    image: gogo-mint-minter-img
    # ports:
    #   - "80:${PORT:-80}"
    restart: always
    container_name: gogo-mint-minter
    env_file:
      - .env
  redis:
    image: redis
    container_name: gogo-minter-redis
    restart: always